# Generated by Django 5.1.7 on 2025-05-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Post Categories'},
        ),
    ]
