# Generated by Django 5.1.5 on 2025-05-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_comment_author_alter_thread_author'),
        ('forum', '0002_alter_postcategory_options'),
    ]

    operations = [
    ]
