# Generated by Django 5.1.5 on 2025-05-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_article_category_alter_article_entry_and_more'),
        ('wiki', '0004_articleimage'),
    ]

    operations = [
    ]
